/// Flutter icons SmilingMind
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  SmilingMind
///      fonts:
///       - asset: fonts/SmilingMind.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class SmilingMind {
  SmilingMind._();

  static const _kFontFam = 'SmilingMind';
  static const String? _kFontPkg = null;

  static const IconData meditate = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData music = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sleep = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home_white = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData meditate_white = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData music_white = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sleep_white = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user_white = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
